In [12]:
import torch
import csv
import numpy
from pathlib import Path
import pandas

In [11]:
with open(Path("./data/house_tiny.csv"),'w') as out:
    writer = csv.writer(out)
    writer.writerows([["NumRooms","Alley","Price"],[None,"Pave",127500],[2,None,106000],[4,None,178100],[None,None,140000]])

In [14]:
data = pandas.read_csv("./data/house_tiny.csv")
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [15]:
inputs, outputs = data.iloc[:,0:2],data.iloc[:,2]

In [22]:
inputs["NumRooms"] = inputs["NumRooms"].fillna(inputs["NumRooms"].mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [24]:
inputs = pandas.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [35]:
inputs["Alley_Pave"] = inputs["Alley_Pave"].astype(dtype=float)
inputs["Alley_nan"] = inputs["Alley_nan"].astype(float)

In [36]:
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0

In [37]:
X, y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [52]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [53]:
b = torch.arange(4)
b

tensor([0, 1, 2, 3])

In [54]:
torch.mv(A,b)

tensor([ 14,  38,  62,  86, 110])

In [59]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = torch.arange(8,dtype=torch.float32).reshape(4,2)
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.]]))

In [60]:
torch.mm(A,B)

tensor([[ 28.,  34.],
        [ 76.,  98.],
        [124., 162.],
        [172., 226.],
        [220., 290.]])

In [65]:
B.T[0]

tensor([0., 2., 4., 6.])

In [67]:
torch.sum(A,dim=1)

tensor([ 6., 22., 38., 54., 70.])

In [71]:
a = torch.ones(2,5,4)
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [72]:
a.sum(dim=0)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [75]:
x = torch.arange(4.0,requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [77]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [78]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])