In [1]:
import torch
from torch import nn

In [2]:
def pool2d(X, pool_size, mode='max'):
    p_h,p_w = pool_size
    a,b = X.shape
    Y = torch.zeros((a-p_h+1,b-p_w+1))
    for i in range(a-p_h+1):
        for j in range(b-p_w+1):
            if mode == 'max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()
            if mode == 'mean':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y


In [3]:
X = torch.arange(9.0).reshape((3,3))
X

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [4]:
pool2d(X,(2,2))

tensor([[4., 5.],
        [7., 8.]])

In [5]:
pool2d(X,(2,2),'mean')

tensor([[2., 3.],
        [5., 6.]])

In [6]:
X = torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [7]:
# 池化层的默认值略微奇怪，初始化的时候注意初始化步幅和填充
pool2d = nn.MaxPool2d(2, stride=1, padding=0)
pool2d(X)

tensor([[[[ 5.,  6.,  7.],
          [ 9., 10., 11.],
          [13., 14., 15.]]]])

In [8]:
X = torch.cat((X,X+1),dim=1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [9]:
# 池化层不改变输出的维度，默认作用于每一个维度
pool2d(X)

tensor([[[[ 5.,  6.,  7.],
          [ 9., 10., 11.],
          [13., 14., 15.]],

         [[ 6.,  7.,  8.],
          [10., 11., 12.],
          [14., 15., 16.]]]])